// Loads the real PNG spritesheets (game2d/assets/*-spritesheet.png) and
// builds the walk + attack animations for every kind — playable races
// (including the evolved-only hobgoblin), wild monster kinds, and a
// handful of decorative-only kinds with no gameplay hookup yet — all
// sharing the same rig/layout (4 fully distinct directional rows:
// down/up/left/right, 8 columns per row: 4 walk frames then 4 attack
// frames). No runtime horizontal flip anywhere — "right" is its own real
// row baked into the PNG (a mirror of "left" applied at generation time).
import type { Race, MonsterKind, Gender, HairColor, SkinTone } from '../shared/constants.js';
import { GENDERS, HAIR_COLORS, SKIN_TONES } from '../shared/constants.js';
import type { TeacherRobeColor } from '../shared/types.js';
import { TEACHER_ROBE_COLORS } from '../shared/types.js';

export const FRAME_WIDTH = 110;
export const FRAME_HEIGHT = 140;
const WALK_FRAME_COUNT = 4;
const PUNCH_FRAME_COUNT = 4;
const COLS_PER_ROW = WALK_FRAME_COUNT + PUNCH_FRAME_COUNT;

export type FacingGroup = 'down' | 'up' | 'left' | 'right';
const ROW_INDEX: Record<FacingGroup, number> = { down: 0, up: 1, left: 2, right: 3 };

// A teacher's own robe-color variant (a follow-up ask: "give each
// teacher a different colored robe") — one fully recolored spritesheet
// per color (see assets/teacher-spritesheet-${color}.png, generated by
// hue-rotating just the robe's own navy tones; skin/hair/trim untouched),
// same frame layout as the base 'teacher' sheet. Each color also has its
// own long-hair variant (a later follow-up ask: "update the female
// teachers to have long hair") — see assets/
// teacher-spritesheet-${color}-longhair.png.
export type TeacherVariantKind = `teacher-${TeacherRobeColor}` | `teacher-${TeacherRobeColor}-longhair`;

// Kinds with a spritesheet but no gameplay hookup yet (no playable race,
// no spawned monster) — assets exist and their walk/attack anims are
// fully created/playable, ready for whatever uses them next.
export type DecorativeKind = 'ogre' | 'shopkeeper' | 'teacher' | TeacherVariantKind;

// A human wizard's actual rendered appearance — gender x skin tone x hair
// color, 18 combinations total, each its own fully-baked spritesheet (see
// tools/gen-human-sprites.mjs). Baked per-combination rather than one
// neutral sheet re-tinted client-side: skin and hair need two
// INDEPENDENTLY colored regions on the same figure, and re-tinting would
// need a second overlay sprite kept in perfect frame-by-frame lockstep
// with the body at every single walk/punch/idle call site in WorldScene
// — baking instead costs nothing extra to generate (the generator script
// just loops) and needs zero new runtime machinery, matching the "one
// texture key per fully-resolved look" shape every other race already
// uses. See effectiveSpriteKind, the one place a Race turns into this.
export type HumanSpriteKind = `human-${Gender}-${SkinTone}-${HairColor}`;

// A "kind" is anything with its own spritesheet — a playable race
// (including the evolved-only hobgoblin and the wizarding-school pivot's
// 'human'), a wild monster kind, or one of the decorative-only kinds
// above.
export type SpriteKind = Race | MonsterKind | DecorativeKind | HumanSpriteKind;

function buildHumanKeyMaps(): { textureKeys: Record<HumanSpriteKind, string>; sheetPaths: Record<HumanSpriteKind, string> } {
  const textureKeys = {} as Record<HumanSpriteKind, string>;
  const sheetPaths = {} as Record<HumanSpriteKind, string>;
  for (const gender of GENDERS) {
    for (const skinTone of SKIN_TONES) {
      for (const hairColor of HAIR_COLORS) {
        const key: HumanSpriteKind = `human-${gender}-${skinTone}-${hairColor}`;
        textureKeys[key] = key;
        sheetPaths[key] = `/${key}-spritesheet.png`;
      }
    }
  }
  return { textureKeys, sheetPaths };
}
const { textureKeys: HUMAN_TEXTURE_KEYS, sheetPaths: HUMAN_SHEET_PATHS } = buildHumanKeyMaps();

function buildTeacherVariantKeyMaps(): { textureKeys: Record<TeacherVariantKind, string>; sheetPaths: Record<TeacherVariantKind, string> } {
  const textureKeys = {} as Record<TeacherVariantKind, string>;
  const sheetPaths = {} as Record<TeacherVariantKind, string>;
  for (const color of TEACHER_ROBE_COLORS) {
    const key: TeacherVariantKind = `teacher-${color}`;
    textureKeys[key] = key;
    sheetPaths[key] = `/teacher-spritesheet-${color}.png`;
    const longHairKey: TeacherVariantKind = `teacher-${color}-longhair`;
    textureKeys[longHairKey] = longHairKey;
    sheetPaths[longHairKey] = `/teacher-spritesheet-${color}-longhair.png`;
  }
  return { textureKeys, sheetPaths };
}
const { textureKeys: TEACHER_VARIANT_TEXTURE_KEYS, sheetPaths: TEACHER_VARIANT_SHEET_PATHS } = buildTeacherVariantKeyMaps();

const TEXTURE_KEYS: Record<SpriteKind, string> = {
  goblin: 'goblin',
  skeleton: 'skeleton',
  hobgoblin: 'hobgoblin',
  zombie: 'zombie',
  dragonborn: 'dragon-man',
  slime: 'slime',
  // Bare 'human' (the Race value itself) is never used to render
  // directly — effectiveSpriteKind always resolves the full gender/skin/
  // hair composite key first. Present only to satisfy Record totality.
  human: 'human-male-white-brown',
  // A later follow-up ask restored race as a real character-creation
  // choice — these 4 new playable races each get one plain spritesheet
  // (no gender/skin/hair baking), same "single fixed look" treatment
  // every non-human race already has.
  elf: 'elf',
  'half-elf': 'half-elf',
  viravis: 'viravis',
  pixie: 'pixie',
  'wild goblin': 'wild-goblin',
  'wild skeleton': 'wild-skeleton',
  imp: 'imp',
  ogre: 'ogre',
  shopkeeper: 'shopkeeper',
  teacher: 'teacher',
  ...TEACHER_VARIANT_TEXTURE_KEYS,
  ...HUMAN_TEXTURE_KEYS,
};
const SHEET_PATHS: Record<SpriteKind, string> = {
  goblin: '/goblin-spritesheet.png',
  skeleton: '/skeleton-spritesheet.png',
  hobgoblin: '/hobgoblin-spritesheet.png',
  zombie: '/zombie-spritesheet.png',
  dragonborn: '/dragon-man-spritesheet.png',
  slime: '/slime-spritesheet.png',
  human: '/human-male-white-brown-spritesheet.png',
  elf: '/elf-spritesheet.png',
  'half-elf': '/half-elf-spritesheet.png',
  viravis: '/viravis-spritesheet.png',
  pixie: '/pixie-spritesheet.png',
  'wild goblin': '/wild-goblin-spritesheet.png',
  'wild skeleton': '/wild-skeleton-spritesheet.png',
  imp: '/imp-spritesheet.png',
  ogre: '/ogre-spritesheet.png',
  shopkeeper: '/shopkeeper-spritesheet.png',
  teacher: '/teacher-spritesheet.png',
  ...TEACHER_VARIANT_SHEET_PATHS,
  ...HUMAN_SHEET_PATHS,
};

// The one place a character's Race turns into an actual render kind —
// every other race maps to itself; 'human' resolves to its full gender/
// skin/hair composite (see HumanSpriteKind above). Called wherever
// WorldScene used to just use `race` directly for texture/animation
// lookups.
export function humanSpriteKindFor(gender: Gender | null, skinTone: SkinTone | null, hairColor: HairColor | null): HumanSpriteKind {
  return `human-${gender ?? 'male'}-${skinTone ?? 'white'}-${hairColor ?? 'brown'}`;
}
export function effectiveSpriteKind(race: Race, gender: Gender | null, skinTone: SkinTone | null, hairColor: HairColor | null): SpriteKind {
  return race === 'human' ? humanSpriteKindFor(gender, skinTone, hairColor) : race;
}

// The attack animation is always the same 4 frames (columns 4-7) — only
// its NAME differs for a slime, which "slaps" rather than "punches"
// (still triggered by the same punch action/server event; this only
// changes what the client calls/labels the clip).
const ATTACK_VERB: Partial<Record<SpriteKind, string>> = { slime: 'slap' };
function attackVerbFor(kind: SpriteKind): string {
  return ATTACK_VERB[kind] ?? 'punch';
}

export function textureKeyFor(kind: SpriteKind): string {
  return TEXTURE_KEYS[kind];
}

export function idleFrameFor(kind: SpriteKind, facing: FacingGroup): number {
  return ROW_INDEX[facing] * COLS_PER_ROW;
}

export function walkAnimKey(kind: SpriteKind, facing: FacingGroup): string {
  return `${TEXTURE_KEYS[kind]}-walk-${facing}`;
}

export function punchAnimKey(kind: SpriteKind, facing: FacingGroup): string {
  return `${TEXTURE_KEYS[kind]}-${attackVerbFor(kind)}-${facing}`;
}

export function preloadCharacterSprites(scene: Phaser.Scene): void {
  for (const kind of Object.keys(SHEET_PATHS) as SpriteKind[]) {
    scene.load.spritesheet(TEXTURE_KEYS[kind], SHEET_PATHS[kind], {
      frameWidth: FRAME_WIDTH,
      frameHeight: FRAME_HEIGHT,
    });
  }
}

// A corpse's lootable body-part icon reuses the sheet itself rather than
// needing a separate asset: a small crop of the down-facing idle frame's
// head/ears region (every generator draws the head in the same y-range,
// see game2d/assets' generator scripts), registered once as a named
// sub-frame of the existing texture.
const BODY_PART_FRAME_HEIGHT = 70;

export function bodyPartFrameKey(kind: SpriteKind): string {
  return `${TEXTURE_KEYS[kind]}-bodypart`;
}

export function defineBodyPartFrames(scene: Phaser.Scene): void {
  for (const kind of Object.keys(SHEET_PATHS) as SpriteKind[]) {
    const texture = scene.textures.get(TEXTURE_KEYS[kind]);
    const frameKey = bodyPartFrameKey(kind);
    if (!texture.has(frameKey)) {
      texture.add(frameKey, 0, 0, 0, FRAME_WIDTH, BODY_PART_FRAME_HEIGHT);
    }
  }
}

export function createCharacterAnims(scene: Phaser.Scene): void {
  for (const kind of Object.keys(SHEET_PATHS) as SpriteKind[]) {
    const textureKey = TEXTURE_KEYS[kind];
    (['down', 'up', 'left', 'right'] as FacingGroup[]).forEach((facing) => {
      const rowStart = ROW_INDEX[facing] * COLS_PER_ROW;

      scene.anims.create({
        key: walkAnimKey(kind, facing),
        frames: scene.anims.generateFrameNumbers(textureKey, {
          start: rowStart,
          end: rowStart + WALK_FRAME_COUNT - 1,
        }),
        frameRate: 8,
        repeat: -1,
      });

      scene.anims.create({
        key: punchAnimKey(kind, facing),
        frames: scene.anims.generateFrameNumbers(textureKey, {
          start: rowStart + WALK_FRAME_COUNT,
          end: rowStart + WALK_FRAME_COUNT + PUNCH_FRAME_COUNT - 1,
        }),
        frameRate: 12,
        repeat: 0,
      });
    });
  }
}
