// Loads the real PNG spritesheets (game2d/assets/*-spritesheet.png,
// generated by node-canvas) and builds the walk + punch animations for
// both races. One combined sheet per race: 4 fully distinct directional
// rows (down/up/left/right), 8 columns per row (4 walk frames, then 4
// punch frames). Unlike an earlier version of this file, there is no
// runtime horizontal flip anywhere — "right" is its own real row baked
// into the PNG (a mirror of "left" applied at generation time), so a
// sprite facing right is just a normal texture frame, not a flipped one.
import type { Race } from '../shared/constants.js';

export const FRAME_WIDTH = 110;
export const FRAME_HEIGHT = 140;
const WALK_FRAME_COUNT = 4;
const PUNCH_FRAME_COUNT = 4;
const COLS_PER_ROW = WALK_FRAME_COUNT + PUNCH_FRAME_COUNT;

export type FacingGroup = 'down' | 'up' | 'left' | 'right';
const ROW_INDEX: Record<FacingGroup, number> = { down: 0, up: 1, left: 2, right: 3 };

const TEXTURE_KEYS: Record<Race, string> = { goblin: 'goblin', skeleton: 'skeleton' };
const SHEET_PATHS: Record<Race, string> = {
  goblin: '/goblin-spritesheet.png',
  skeleton: '/skeleton-spritesheet.png',
};

export function textureKeyFor(race: Race): string {
  return TEXTURE_KEYS[race];
}

export function idleFrameFor(race: Race, facing: FacingGroup): number {
  return ROW_INDEX[facing] * COLS_PER_ROW;
}

export function walkAnimKey(race: Race, facing: FacingGroup): string {
  return `${TEXTURE_KEYS[race]}-walk-${facing}`;
}

export function punchAnimKey(race: Race, facing: FacingGroup): string {
  return `${TEXTURE_KEYS[race]}-punch-${facing}`;
}

export function preloadCharacterSprites(scene: Phaser.Scene): void {
  for (const race of Object.keys(SHEET_PATHS) as Race[]) {
    scene.load.spritesheet(TEXTURE_KEYS[race], SHEET_PATHS[race], {
      frameWidth: FRAME_WIDTH,
      frameHeight: FRAME_HEIGHT,
    });
  }
}

export function createCharacterAnims(scene: Phaser.Scene): void {
  for (const race of Object.keys(SHEET_PATHS) as Race[]) {
    const textureKey = TEXTURE_KEYS[race];
    (['down', 'up', 'left', 'right'] as FacingGroup[]).forEach((facing) => {
      const rowStart = ROW_INDEX[facing] * COLS_PER_ROW;

      scene.anims.create({
        key: walkAnimKey(race, facing),
        frames: scene.anims.generateFrameNumbers(textureKey, {
          start: rowStart,
          end: rowStart + WALK_FRAME_COUNT - 1,
        }),
        frameRate: 8,
        repeat: -1,
      });

      scene.anims.create({
        key: punchAnimKey(race, facing),
        frames: scene.anims.generateFrameNumbers(textureKey, {
          start: rowStart + WALK_FRAME_COUNT,
          end: rowStart + WALK_FRAME_COUNT + PUNCH_FRAME_COUNT - 1,
        }),
        frameRate: 12,
        repeat: 0,
      });
    });
  }
}
