// Pure rendering helpers/constants shared by WorldScene — no DOM, no
// mutable module state, just math and small Phaser Graphics drawing.
import Phaser from 'phaser';
import type { MapName, Direction } from '../../shared/constants.js';
import { FLORO_SHOP_MAPS, GRIMOAK_CASTLE_MAPS } from '../../shared/constants.js';
import type { FacingGroup } from '../characterSprites.js';

export const TILE_SIZE = 32;
// Classrooms (see shared/constants.ts's CLASSROOM_MAPS) are laid out at a
// third of the standard room's tile footprint (shared/maps.ts's
// CLASSROOM_ROWS/COLS) — a follow-up ask that also required they "still
// fill up the whole screen." Zooming the camera in by roughly the same
// factor the footprint shrank by restores the same on-screen coverage a
// full-size room gets at zoom 1 (see WorldScene's applyCameraBounds).
export const CLASSROOM_ZOOM = 3;
export const TREE_TEXTURE_KEY = 'tree';
export const DAGGER_TEXTURE_KEY = 'held-dagger';
export const BONE_SHIELD_TEXTURE_KEY = 'held-bone-shield';
export const TORCH_HELD_TEXTURE_KEY = 'held-torch';
// A wand, held in the same hand/position as a dagger (mutually
// exclusive — see shared/equipment.ts's WAND_ITEM) — its own overlay
// sprite rather than reusing the dagger one, same "shares a slot, still
// a distinct held item" shape as the torch/shield pairing.
export const WAND_TEXTURE_KEY = 'held-wand';
// The small glow effect at the wand's tip while lucem is active (item
// 12) — a plain Phaser Graphics-drawn circle (see WorldScene's
// wandGlowSprite), not a sprite asset, same "Graphics for a lighting
// effect" treatment the hp/mana bars already use, rather than pre-baked
// pixel art for something that's a soft radial blur by nature.
export const WAND_GLOW_RADIUS_PX = 7;
export const WAND_GLOW_COLOR = 0xfff2b0;

// Floro shop building (item 11) — 2 frames (0: facing right, 1: facing
// left, see tools/gen-shop-assets.mjs), each 3x3.5 tiles.
export const SHOP_BUILDING_TEXTURE_KEY = 'shop-building';
export const SHOP_BUILDING_FRAME_WIDTH = 96;
export const SHOP_BUILDING_FRAME_HEIGHT = 112;
export const SHOP_BUILDING_FACING_RIGHT_FRAME = 0;
export const SHOP_BUILDING_FACING_LEFT_FRAME = 1;

// A single fancy double door (a follow-up ask) used for EVERY map exit
// now — shop doors and every other transition alike — replacing both the
// old plain 'door' SVG and the shop-only wooden-door spritesheet (which
// used to be the only distinction between the two). See
// tools/gen-grand-door.mjs.
export const GRAND_DOOR_TEXTURE_KEY = 'grand-door';

// Grimoak Castle's exterior (item 4) and its decorations (item 6) — real
// static PNGs generated by tools/gen-castle-exterior.mjs (no Aseprite/
// pixel-mcp available in this environment). The castle is one wide image:
// a central keep + 2 (original) towers, flanked by 2 more wings and 1
// more outer tower per side (item 2's correction — the width grew by
// adding distinct buildings, not by stretching the original artwork;
// ROWS/height is unchanged from the original single-keep image). Flight/
// flicker motion comes from Phaser tweens applied to these otherwise-
// static textures, not frame animation — the same treatment this
// project's wall torches already use.
export const CASTLE_EXTERIOR_TEXTURE_KEY = 'castle-exterior';
export const CASTLE_EXTERIOR_WIDTH = 1920;
export const CASTLE_EXTERIOR_HEIGHT = 672;
// Halved again per a follow-up request ("keep the same number of
// buildings/towers, but make it half the size") — same wide asset above,
// just rendered smaller. shared/maps.ts's own castle-collision footprint
// (see isCastleExteriorBlocked) is expressed in these same already-scaled
// tile dimensions.
export const CASTLE_EXTERIOR_SCALE = 1;
// Each of the 4 towers' horizontal center, as a fraction of the whole
// image's width — left outer, left inner, right inner, right outer, in
// that order, computed from tools/gen-castle-exterior.mjs's own layout
// math so a crow can be anchored at the top of every tower (a follow-up
// ask), not just two fixed points sized for the old 2-tower design.
export const CASTLE_TOWER_X_FRACTIONS = [0.03125, 0.284375, 0.715625, 0.96875];
// How far down from the image's top edge a crow should hover — just
// below the spire tips, same proportion the original 2-tower design used.
export const CASTLE_TOWER_TOP_FRACTION = 0.06;
export const CROW_TEXTURE_KEY = 'crow';
export const FIREPLACE_MANTLE_TEXTURE_KEY = 'fireplace-mantle';
export const FIREPLACE_FLAME_TEXTURE_KEY = 'fireplace-flame';
export const STAIRS_TEXTURE_KEY = 'stairs';
// A classroom teacher's desk (a follow-up ask) — furniture, not a
// separate server entity; positioned from server/worlds/teachers.ts's
// deskPositionFor, always one tile in front of its teacher.
export const CLASSROOM_DESK_TEXTURE_KEY = 'classroom-desk';
// The Utilization classroom's clickable spellbook podium (item 8) — see
// shared/spells.ts's LUCEM_BOOK_MAP/POSITION.
export const SPELLBOOK_PODIUM_TEXTURE_KEY = 'spellbook-podium';
// A social gathering spot's benches (a follow-up ask upgraded these from
// plain chairs) — see shared/lighting.ts's benchPositionsFor.
export const BENCH_TEXTURE_KEY = 'bench';
// Spell/attack projectiles (a follow-up ask) — see WorldScene's
// playProjectileEffect, triggered off a 'combat' event's own `skill`.
export const FIREBALL_TEXTURE_KEY = 'fireball';
export const BOLT_TEXTURE_KEY = 'bolt';
// The secret room's treasure chest (a later follow-up ask) — two frames
// picked by the player's own secretChestUnlocked flag, see
// shared/maps.ts's CAVERNA_CHEST_POSITION.
export const CHEST_LOCKED_TEXTURE_KEY = 'chest-locked';
export const CHEST_UNLOCKED_TEXTURE_KEY = 'chest-unlocked';

export const CHAR_SCALE = 0.275;
export const CORPSE_SCALE = 0.35;
// One server round trip per tile-step, throttled the same way holding a
// key down is throttled everywhere else in this project — the walk
// animation plays for exactly this long while tweening between tiles, so
// it reads as a step, not a teleport.
export const MOVE_COOLDOWN_MS = 220;
// Other players/monsters only report a NEW position every so often (see
// the server's own wander/broadcast tick) — tweening the visible step
// over this much shorter duration is what turns "teleports" into "walks".
export const REMOTE_STEP_TWEEN_MS = 260;

export const HP_BAR_WIDTH = 40;
export const HP_BAR_HEIGHT = 5;
export const HP_BAR_OFFSET_Y = -25;
export const MANA_BAR_COLOR = 0x4a8fd4;
export const BAR_STACK_GAP = 2;

// A hand-rolled inline SVG cursor rather than an image asset — a small
// enough shape that hand-authored SVG is clearer than a sprite round-trip.
// Hotspot (12, 12) sits on the blade so the tip visually points at
// whatever's under the cursor.
const SWORD_CURSOR_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g transform="rotate(45 12 12)">
    <rect x="10.5" y="1" width="3" height="13" rx="0.5" fill="#e4e4e4" stroke="#2a2a2a" stroke-width="0.75"/>
    <rect x="11.4" y="1" width="1.2" height="13" fill="#ffffff" opacity="0.6"/>
    <rect x="7" y="14" width="10" height="2.4" rx="0.6" fill="#8a6a3a" stroke="#2a2a2a" stroke-width="0.5"/>
    <rect x="10.3" y="16.4" width="3.4" height="6.2" rx="1" fill="#5a4020" stroke="#2a2a2a" stroke-width="0.5"/>
  </g>
</svg>`;
export const SWORD_CURSOR = `url("data:image/svg+xml,${encodeURIComponent(SWORD_CURSOR_SVG)}") 12 12, pointer`;

// A quill-feather cursor for the spellbook podium — same hand-rolled
// inline SVG treatment as the sword cursor above.
const FEATHER_CURSOR_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g transform="rotate(35 12 12)">
    <path d="M12 1 C17 3.5 17 12.5 12 15 C7 12.5 7 3.5 12 1 Z" fill="#f2ecd8" stroke="#8a8060" stroke-width="0.6"/>
    <path d="M12 2 L12 15" stroke="#c9a24a" stroke-width="0.6"/>
    <path d="M12 2 L9 5 M12 4.5 L9 7.5 M12 7 L9.5 10 M12 9.5 L10 12" stroke="#c9a24a" stroke-width="0.4" opacity="0.7"/>
    <rect x="11.3" y="15" width="1.4" height="7" rx="0.5" fill="#5a4020" stroke="#2a2a2a" stroke-width="0.4"/>
  </g>
</svg>`;
export const FEATHER_CURSOR = `url("data:image/svg+xml,${encodeURIComponent(FEATHER_CURSOR_SVG)}") 12 12, pointer`;

// Facing IS the sheet's own row now — down/up/left/right are each real,
// fully distinct frames (see characterSprites.ts), not a 3-row sheet with
// a flipped "side" shared between left and right.
export type Facing = FacingGroup;

export function floorTextureFor(mapName: MapName): string {
  if (mapName === 'Labyrinth' || (GRIMOAK_CASTLE_MAPS as readonly string[]).includes(mapName)) return 'stone';
  if (mapName === 'Floro' || mapName === 'Kortho' || (FLORO_SHOP_MAPS as readonly string[]).includes(mapName)) return 'concrete';
  return 'grass';
}

export function facingForDirection(direction: Direction): Facing {
  if (direction === 'north') return 'up';
  if (direction === 'south') return 'down';
  return direction === 'west' ? 'left' : 'right';
}

export function drawStatBar(bar: Phaser.GameObjects.Graphics, ratio: number, color: number): void {
  bar.clear();
  bar.fillStyle(0x000000, 0.55);
  bar.fillRect(-HP_BAR_WIDTH / 2, 0, HP_BAR_WIDTH, HP_BAR_HEIGHT);
  bar.fillStyle(color, 1);
  bar.fillRect(-HP_BAR_WIDTH / 2 + 1, 1, Math.max(0, (HP_BAR_WIDTH - 2) * ratio), HP_BAR_HEIGHT - 2);
}

export function drawHpBar(bar: Phaser.GameObjects.Graphics, hp: number, maxHp: number): void {
  const ratio = maxHp > 0 ? Math.max(0, Math.min(1, hp / maxHp)) : 0;
  const color = ratio > 0.5 ? 0x3ecf5e : ratio > 0.25 ? 0xd9a53c : 0xd9403c;
  drawStatBar(bar, ratio, color);
}
